#!/bin/sh

# chkconfig:   35 85 15
# description:  mongod server

# Source function library.
. /etc/rc.d/init.d/functions

# Source networking configuration.
. /etc/sysconfig/network

# Check that networking is up.
[ "$NETWORKING" = "no" ] && exit 0

mongod="/usr/local/mongodb/rhel62-3.6.3/bin/mongod"
prog=$(basename $mongod)

# 配置文件
MONGOD_CONF_FILE="/home/nginx/mongo/config/agile.conf"
# pid文件
MONGOD_ID="/home/nginx/mongo/mongod.pid"
# 锁定文件
lockfile=/var/lock/subsys/mongodb


start() {
    [ -x $mongod ] || exit 5
    [ -f $MONGOD_CONF_FILE ] || exit 6
    echo -n $"Starting $prog: "
    daemon $mongod -f $MONGOD_CONF_FILE
    retval=$?
    echo
    [ $retval -eq 0 ] && touch $lockfile
    return $retval
}

stop() {
    echo -n $"Stopping $prog: "
    killproc $prog -QUIT
    retval=$?
    echo
    [ $retval -eq 0 ] && rm -f $lockfile
    return $retval
}

restart() {
    stop
    sleep 1
    start
}


rh_status() {
    status $prog
}

rh_status_q() {
    rh_status >/dev/null 2>&1
}

case "$1" in
    start)
        rh_status_q && exit 0
        $1
        ;;
    stop)
        rh_status_q || exit 0
        $1
        ;;
    restart)
        $1
        ;;
    status)
        rh_status
        ;;
    *)
        echo $"Usage: $0 {start|stop|status|restart}"
        exit 2
esac
