#!/bin/sh

# chkconfig:   35 85 15
# description:  mongod server

# Source function library.
. /etc/rc.d/init.d/functions

# Source networking configuration.
. /etc/sysconfig/network

# Check that networking is up.
[ "$NETWORKING" = "no" ] && exit 0

mongod="/usr/local/mongodb/mongodb-3.6.5/bin/mongod"
test -e "$mongod" || { echo "$mongod not existing";
	if [ "$1" = "stop" ]; then exit 0;
	else exit 6; fi; }
prog=$(basename $mongod)

# 配置文件
MONGOD_CONF_FILE="/usr/local/mongodb/mongodb-3.6.5/repl.conf"
test -e "$MONGOD_CONF_FILE" || { echo "$MONGOD_CONF_FILE not existing";
	if [ "$1" = "stop" ]; then exit 0;
	else exit 6; fi; }
# pid文件
MONGOD_ID="/var/run/mongod.pid"
# 锁定文件
lockfile=/var/lock/subsys/mongodb


start() {
    [ -x $mongod ] || exit 5
    [ -f $MONGOD_CONF_FILE ] || exit 6
    echo -n $"Starting $prog: "
    daemon $mongod -f $MONGOD_CONF_FILE > /dev/null
    retval=$?
    echo
    [ $retval -eq 0 ] && touch $lockfile
    return $retval
}

stop() {
    echo -n $"Stopping $prog: "
    killproc $prog -QUIT
    retval=$?
    echo
    [ $retval -eq 0 ] && rm -f $lockfile
    return $retval
}

restart() {
    stop
    sleep 1
    start
}


rh_status() {
    status $prog
}

rh_status_q() {
    rh_status >/dev/null 2>&1
}

case "$1" in
    start)
        rh_status_q && exit 0
        $1
        ;;
    stop)
        rh_status_q || exit 0
        $1
        ;;
    restart)
        $1
        ;;
    status)
        rh_status
        ;;
    *)
        echo $"Usage: $0 {start|stop|status|restart}"
        exit 2
esac
